### ISSUE TITLE
Prometheus Server unable to scrape metrics

### ISSUE THREAD

**Issue by wamak9** [jsclayton/prometheus-plex-exporter#28]
This is current Prometheus config I am using.

```yaml
- job_name: prom-plex
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 30m
  scrape_timeout: 1m
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - XXXXXXXXXX:9000
```

This is what I see on Prometheus UI

```bash
Last Scrape | Scrape Duration | Error
-- | -- | --
http://XXXXXXXXXX:9000/metrics | DOWN | instance="XXXXXXXXXX:9000"job="prom-plex" | 19m 13s ago | 3.873ms | server returned HTTP status 404 Not Found
```
not sure what I am missing here ?

on the doccker logs for plex-exporter, I also see

```bash
level=info msg="Successfully connected" machineID=xxxxxxxxx server=xxxxxxxxxx
unknown websocket event name: status
unknown websocket event name: progress
unknown websocket event name: status
```

docker-compose file
```yaml
version: "3"

services:
  prom-plex:
    image: ghcr.io/jsclayton/prometheus-plex-exporter:latest
    container_name: plex-exporter
    restart: always
    network_mode: host
    environment:
      PLEX_SERVER: "http://xxxxxxxxxx:32400/web"
      PLEX_TOKEN: "XXXXXXX"
    ports:
      - 9000:9000/tcp
    volumes:
      - plex-shared:/plex:ro
      - plex-data:/config:ro


volumes:

  plex-data:
    name: prom-plex-data

  plex-shared:
    name: prom-plex-shared

```

Can somone help me figure out what configuration I need to change ?
