### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by samcro1967** [jsclayton/prometheus-plex-exporter#5]
I have the container running and the container logs show it is successfully connected to Plex.  When I go to the URL I get "404 page not found".  Any ideas?

Docker Compose
```
  prom-plex-exporter:
    hostname: prom-plex-exporter
    image: ghcr.io/jsclayton/prometheus-plex-exporter
    container_name: prom-plex-exporter
    restart: always
    environment:
      - PLEX_SERVER=http://192.168.1.104:32400
      - PLEX_TOKEN=${PLEX_TOKEN}
    ports:
      - 9004:9000
```
